codestates-seb/seb45_main_010

server/build.gradle, server/src/docs/asciidoc/index.adoc, server/src/main/java/com/codestates/connectInstructor/ConnectInstructorApplication.java, server/src/main/java/com/codestates/connectInstructor/event/SignupEvent.java, server/src/main/java/com/codestates/connectInstructor/event/SignupEventListener.java, server/src/main/java/com/codestates/connectInstructor/student/controller/StudentController.java, server/src/main/java/com/codestates/connectInstructor/student/service/StudentService.java, server/src/main/resources/static/docs/index.html, server/src/test/java/com/codestates/connectInstructor/student/controller/StudentControllerTest.java, server/src/test/java/com/codestates/connectInstructor/util/ApiDocumentUtils.java
아직 이메일 인증 과정, 이메일 본문은 완성되지 않음
일단은 전송만!
=> [Feat] add 회원 가입 후 메일 전송

client/src/App.tsx, client/src/components/Modal/AlertModal.tsx, client/src/components/Modal/ChangeModal.tsx, client/src/components/Modal/ReqModal.tsx, client/src/components/Modal/SInfoModal.tsx, client/src/components/Modal/TInfoModal.tsx
강사수업요청, 학생수업요청, 신청하기 모달은 내용이 약간씩 다르기에 분류해서 작성
알림창과 변경 알림창은 제목과 내용 버튼을 사용시 입력하여 바뀌도록 작성
예)     
<AlertModal
title={'제목'}
text={'내용'}
btnName={'클릭버튼'}
btnCheck={'확인버튼'}
/>
=> [Feat] add modal

client/src/components/Counter.tsx, client/src/hooks/hooks.tsx, client/src/main.tsx, client/src/redux/slice/CounterSlice.tsx, client/src/redux/store.tsx
리덕스툴킷 기본셋팅 후
예시 Counter적용 (머지 후 삭제예정)
=> Fe add redux toolkit

client/data/data1.json, client/data1.json, client/src/pages/Login.tsx, client/src/pages/SignUp.tsx, client/src/pages/SignUp/SignUp_MUIform_Error.tsx
이메일 회원가입 세부기능 구현 
1. 이름, 이메일, 비밀번호 확인기능 
2. 이메일 중복확인 
3. 회원가입완료 및 로그인 화면이동 구현
=> Fe add email duplicate

client/data/data1.json, client/src/pages/SignUp.tsx
closes #18 
이메일을 이용한 회원가입 코드 수정
=> #18 Refactor_EmailSignup

server/src/main/java/com/codestates/connectInstructor/advice/GlobalExceptionAdvice.java, server/src/main/java/com/codestates/connectInstructor/match/controller/MatchController.java, server/src/main/java/com/codestates/connectInstructor/match/dto/MatchDto.java, server/src/main/java/com/codestates/connectInstructor/match/entity/Match.java, server/src/main/java/com/codestates/connectInstructor/match/mapper/MatchMapper.java, server/src/main/java/com/codestates/connectInstructor/match/repository/MatchRepository.java, server/src/main/java/com/codestates/connectInstructor/match/service/MatchService.java, server/src/main/java/com/codestates/connectInstructor/region/controller/RegionController.java, server/src/main/java/com/codestates/connectInstructor/region/dto/RegionDto.java, server/src/main/java/com/codestates/connectInstructor/region/entity/Region.java, server/src/main/java/com/codestates/connectInstructor/region/mapper/RegionMapper.java, server/src/main/java/com/codestates/connectInstructor/region/repository/RegionRepository.java, server/src/main/java/com/codestates/connectInstructor/region/service/RegionService.java, server/src/main/java/com/codestates/connectInstructor/student/controller/StudentController.java, server/src/main/java/com/codestates/connectInstructor/student/dto/StudentDto.java, server/src/main/java/com/codestates/connectInstructor/student/entity/Student.java, server/src/main/java/com/codestates/connectInstructor/subject/controller/SubjectController.java, server/src/main/java/com/codestates/connectInstructor/subject/dto/SubjectDto.java, server/src/main/java/com/codestates/connectInstructor/subject/entity/Subject.java, server/src/main/java/com/codestates/connectInstructor/subject/mapper/SubjectMapper.java, server/src/main/java/com/codestates/connectInstructor/subject/repository/SubjectRepository.java, server/src/main/java/com/codestates/connectInstructor/subject/service/SubjectService.java, server/src/main/java/com/codestates/connectInstructor/teacher/controller/TeacherController.java, server/src/main/java/com/codestates/connectInstructor/teacher/dto/TeacherDto.java, server/src/main/java/com/codestates/connectInstructor/teacher/entity/Teacher.java, server/src/main/java/com/codestates/connectInstructor/teacher/entity/TeacherRegion.java, server/src/main/java/com/codestates/connectInstructor/teacher/entity/TeacherSubject.java, server/src/main/java/com/codestates/connectInstructor/utils/UriCreator.java
=> [Feat] add 예외처리추가. GlobalExceptionAdvice

client/src/components/Items/OnlineDiv.tsx, client/src/components/Profile/ProfileHeader.tsx, client/src/components/Profile/ProfileTab/Calendar.tsx, client/src/components/Profile/ProfileTab/OptionList.tsx, client/src/components/Profile/ProfileTab/ScheduleList.tsx, client/src/components/Profile/ProfileTabs.tsx, client/src/pages/Profile/Profile.tsx
**일정부분** 
- 데이터형식 체크 
- 드롭다운 추가
**프로필부분**
- on/offline 상태관리
=> Fe add schedule

server/build.gradle, server/src/main/java/com/codestates/connectInstructor/ConnectInstructorApplication.java, server/src/main/java/com/codestates/connectInstructor/security/config/AppConfiguration.java, server/src/main/java/com/codestates/connectInstructor/security/config/SecurityConfiguration.java, server/src/main/java/com/codestates/connectInstructor/security/oauth2/handler/OAuth2FailureHandler.java, server/src/main/java/com/codestates/connectInstructor/security/oauth2/handler/OAuth2SuccessHandler.java, server/src/main/java/com/codestates/connectInstructor/security/oauth2/resolver/CustomRequestResolver.java, server/src/main/java/com/codestates/connectInstructor/security/oauth2/service/CustomOauth2Service.java, server/src/main/java/com/codestates/connectInstructor/security/oauth2/user/CustomOAuth2User.java, server/src/main/java/com/codestates/connectInstructor/student/dto/StudentDto.java, server/src/main/java/com/codestates/connectInstructor/student/entity/Student.java, server/src/main/java/com/codestates/connectInstructor/teacher/dto/TeacherDto.java, server/src/main/java/com/codestates/connectInstructor/teacher/entity/Teacher.java, server/src/main/resources/application.yml
일단 디폴트로 student로 가입하게 만들어뒀습니다.
리팩토링.... 아직 많이 필요한데 협의할 부분이 남아있어서 추후 수정해야할 거 같아서 일단 pr합니다.
student 엔티티 nullable=true로 남겨두면 회원가입할 때 에러가 생겨 false로 변경했습니다.
=> [Feat] add kakao 로그인

client/src/pages/GetPassword.tsx, client/src/pages/Login.tsx, client/src/pages/Private.tsx, client/src/pages/SignUp.tsx
메인 화면과 동일한 width로 화면이 꽉 차도록 디자인 조정 (375, 350, 330으로 크기 조정)
=> Design_Width_Trim_Member

client/data/data1.json, client/src/components/Types/Types.tsx, client/src/pages/Login.tsx, client/src/pages/Private.tsx, client/src/pages/SignUp.tsx, client/src/redux/slice/MemberSlice.tsx, client/src/redux/store.tsx
Private Page에 로그인 정보 연동을 위해 Login_Redux Thunk적용
=> Fe add private function

client/data/data1.json, client/src/components/Modal/ChangeModal.tsx, client/src/pages/Login.tsx, client/src/pages/Private.tsx, client/src/redux/slice/MemberSlice.tsx
1. 로그인 후 회원 기준 정보를 이용해 회원 정보 Upate - Thunk 적용 
2. 회원정보 변경화면에서 1.번 정보를 연동하여 기본정보 변경
3. 회원 정보창에서 정보변경을 위한 모달적용 
4. 디자인 오류 수정 ( 이미지 변경 버튼이 검색창 모달위로 표시 )
#56 
** MUI사용시, 버튼 커스텀이 어려워 피그마 디자인 변경예정
=> Fe private page function

client/src/components/Menu/Search.tsx, client/src/pages/Private.tsx
개인정보변경 페이지 카메라 아이콘이 메뉴모달 앞으로 오는 오류 수정
검색 기능 여러가지 입력할 수 있도록 수정 
input id 에대한 타입을 찾지 못함
=> Fe modify search

client/src/Types/Types.tsx, client/src/components/Footer/Footer.tsx, client/src/components/Footer/FooterGithub.tsx, client/src/components/Footer/FooterIcon.tsx, client/src/components/Menu/Search.tsx, client/src/components/Menu/SearchForm.tsx, client/src/components/Menu/SearchSelect.tsx, client/src/components/Menu/SideList.tsx, client/src/components/Menu/SideMembership.tsx, client/src/components/Menu/Sidebar.tsx, client/src/configs/Footer/configs.tsx
footer
sidebar
search
컴포넌트를 더 작게 분할 후 코드 리펙토링 진행하였습니다
=> Fe refactor

client/src/components/Modal/AlertModal.tsx, client/src/pages/Private.tsx, data/data1.json
개인정보 변경 (닉네임, 전화번호, 비밀번호 변경) 기능 구현 #
=> Fe private patch test

client/src/components/Modal/AlertModal.tsx, client/src/components/Modal/ChangeModal.tsx
=> FIX_ModalChange

client/src/components/Auth/CheckAuth.tsx, client/src/components/DetailPage/RequestBtn.tsx, client/src/pages/DetailPage/DetailPage.tsx, client/src/pages/Login.tsx, client/src/pages/Private.tsx, client/src/redux/slice/MemberSlice.tsx
=> FEAT_토크 자동로그인

client/src/Types/Types.tsx, client/src/components/Auth/GetAuth.tsx, client/src/components/Modal/ChangeModal.tsx, client/src/pages/Login.tsx, client/src/pages/Private.tsx, client/src/redux/slice/MemberSlice.tsx
로그인 기능을 분산하여 저장하면서 Alert가 거듭하여 나타나는것과
세부 저장기능의 비동기적인 오류를 바로잡았습니다.
=> Fe 로그인기능수정

server/src/docs/asciidoc/index.adoc, server/src/main/java/com/codestates/connectInstructor/teacher/controller/TeacherController.java, server/src/main/java/com/codestates/connectInstructor/teacher/dto/TeacherDto.java, server/src/main/java/com/codestates/connectInstructor/teacher/mapper/TeacherMapper.java, server/src/main/java/com/codestates/connectInstructor/teacher/service/TeacherService.java, server/src/main/resources/static/docs/index.html, server/src/test/java/com/codestates/connectInstructor/teacher/controller/TeacherControllerTest.java
강사의 과목/지역들 문자열 리스트로 나오게. 
강사정보 수정 시 수정시간 갱신. 
강사의 지역/과목 수정방식 변경.
=> [Feat] 강사의 과목/지역들 문자열 리스트로 나오게. 강사정보 수정 시 수정시간 갱신. 강사의 지역/과목 수정방식 변경

client/src/components/Auth/CheckAuth.tsx, client/src/components/Auth/SetAuth.tsx, client/src/pages/Login.tsx, client/src/pages/Private.tsx, client/src/redux/slice/MemberSlice.tsx, client/src/redux/slice/OauthSlice.tsx, client/src/redux/store.tsx
1.자동 로그인 및 입력로그인 알람중복 제거 
2. Auth code중복제거
** Redux에 보내는 부분에서 typescript 유형Error가 나타납니다.
어떻게 해결하는지 궁금합니다.
=> FIX 로그인알람오류제거

client/src/components/Modal/ImageChangeModal.tsx, client/src/pages/Login.tsx, client/src/pages/Private.tsx, client/src/redux/slice/MemberSlice.tsx
#53 
1. 로그인시 Thunk함수의 회원정보 실시간 변경을 dispatch하여 여러번 로딩으로 인한 알람중복 발생
- SetTimeout설정으로 80%이상 해결되었으나 간혹 나타남 
2. 개인정보변경 
- 이름, 전화번호, 패스워드, imageURL변경 axios response있는 경우 redux 상태 update를 통해 화면에 바로 렌더링 반영
=> Fe private patch

client/src/components/Modal/ChangeModal.tsx, client/src/components/Modal/ImageChangeModal.tsx, client/src/pages/Private.tsx, client/src/pages/SignUp.tsx, client/src/redux/slice/MemberSlice.tsx
=> FIX 불필요한 변수제거

client/src/components/Auth/Logout.tsx, client/src/components/Auth/logoutUtils.tsx, client/src/components/Modal/ChangeModal.tsx, client/src/pages/Private.tsx, client/src/redux/slice/MemberSlice.tsx
close #117
1. 토큰삭제
2. redux상태 초기화
3. 토큰없는 상태에서 로그아웃버튼 비활성화
=> FEAT_로그아웃기능구현

client/src/components/Menu/SideMembership.tsx, client/src/pages/Login.tsx
#117 close
GNB 버튼에 로그아웃 기능구현 
로그인/로그아웃 표시기준은 MemeberSlice에 userID가 존재여부
userID가 존재하면 로그인, 존재하지 않으면 로그아웃 
(토큰여부로 검증하지 않음)
=> Feat_GNB_LogOut

client/src/components/Auth/Logout.tsx, client/src/components/Menu/SideMembership.tsx
=> Feat_FixLogOut

client/src/components/Modal/ChangeModal.tsx, client/src/components/Modal/SocialSignUpModal.tsx, client/src/pages/GetPassword.tsx, client/src/pages/Login.tsx, client/src/pages/Private.tsx, client/src/pages/SignUp.tsx
변수명 객체화 
Password변경부분 비동기 설정 #128
=> Fe getpassword

client/src/components/Auth/Logout.tsx, client/src/components/Auth/SetAuth.tsx, client/src/components/Modal/ChangeModal.tsx, client/src/components/Modal/ImageChangeModal.tsx, client/src/components/Modal/SocialSignUpModal.tsx, client/src/pages/GetPassword.tsx, client/src/pages/Login.tsx, client/src/pages/Private.tsx, client/src/pages/SignUp.tsx, client/src/redux/slice/MemberSlice.tsx
=> Refactor structure

client/src/Types/Types.tsx, client/src/components/DetailPage/DetailScheduleList.tsx, client/src/components/DetailPage/DetailSetSchedule.tsx, client/src/components/DetailPage/RequestBtn.tsx, client/src/components/DetailPage/TeacherInfo1.tsx, client/src/components/DetailPage/TeacherInfo2.tsx, client/src/components/Footer/FooterMember.tsx, client/src/components/ListPage/TeacherCard.tsx, client/src/components/Menu/Search/Search.tsx, client/src/components/Menu/Search/SearchForm.tsx, client/src/components/Menu/Search/SearchSelect.tsx, client/src/components/Menu/Sidebar/Sidebar.tsx, client/src/components/Modal/ReqModal/ReqForm.tsx, client/src/components/Modal/ReqModal/ReqModal.tsx, client/src/components/Modal/ReqModal/ReqScheduleList.tsx, client/src/components/Modal/ReqModal/ReqSelect.tsx, client/src/components/Modal/ReqModal/ReqSetSchedule.tsx, client/src/components/Modal/ReqModal/SubmitModal.tsx, client/src/configs/Footer/configs.tsx, client/src/configs/Listpage/config.tsx, client/src/pages/DetailPage/DetailPage.tsx, client/src/redux/slice/lessonRequestSlice.tsx, client/src/redux/thunk/DetailPageThunk.tsx, client/src/redux/thunk/ListPageThunk.tsx, client/src/redux/thunk/lessonRequestThunk.tsx
sidebar, search 디자인 수정
DetailPage, lessonRequest 모달 스케줄 기능 추가
=> Fe modify designmodify

client/src/components/Modal/SocialSignUpModal.tsx, client/src/pages/SignUp.tsx
signup 강사로 가입하기 디자인 조정 
카카오 로그인 주소수정
=> FIX_Design Trim

client/src/components/Items/EditandSave.tsx, client/src/components/Modal/InfoModal.tsx, client/src/components/Profile/ProfileHeader.tsx, client/src/components/Profile/ProfileTab/OptionList.tsx, client/src/components/Profile/ProfileTab/RequestList.tsx, client/src/components/Schedule/SetSchedule.tsx, client/src/redux/slice/CategoriesSlice.tsx, client/src/redux/slice/ProfileSilce.tsx, client/src/redux/slice/TeacherSlice.tsx, client/src/redux/slice/lessonRequestSlice.tsx, client/src/redux/thunk/ProfilePageThunk.tsx
=> [Fix] modify typeError modify

server/src/main/java/com/codestates/connectInstructor/student/entity/Student.java, server/src/main/java/com/codestates/connectInstructor/teacher/entity/Teacher.java
[BE] 테이블의 option컬럼명은 mysql 예약어라서 options로 변경
=> [BE] 테이블의 option컬럼명은 mysql 예약어라서 options로 변경

server/src/main/resources/application.yml
=> BE_ddl-auto값을 none으로

client/src/components/Modal/ChangeModal.tsx, client/src/pages/GetPassword.tsx, client/src/pages/Login.tsx
=> FIX_minorChange

client/src/components/Modal/ImageChangeModal.tsx, client/src/pages/Login.tsx, client/src/pages/SignUp.tsx
=> FIX_remove log

server/src/main/java/com/codestates/connectInstructor/teacher/repository/TeacherRepository.java, server/src/main/resources/application.yml
=> BE_강사 검색 쿼리 개선

server/src/main/java/com/codestates/connectInstructor/teacher/repository/TeacherRepository.java, server/src/main/java/com/codestates/connectInstructor/teacher/service/TeacherService.java, server/src/main/resources/application.yml
=> BE_ 강사검색 쿼리 수정

client/src/Types/Types.tsx, client/src/components/ListPage/TeacherCard.tsx, client/src/components/Modal/ReqModal/ReqModal.tsx, client/src/components/Modal/ReqModal/ReqScheduleList.tsx, client/src/components/Modal/ReqModal/ReqSetSchedule.tsx, client/src/pages/SignUp.tsx, client/src/redux/slice/lessonRequestSlice.tsx, client/src/redux/thunk/lessonRequestThunk.tsx
강의 신청 버튼 버그 해결
이메일 회원가입 버튼 이메일인증 회원가입으로 수정
=> Fe modify fixmodify
